import express from "express";
import authMiddleware from "../middleware/auth.js";
import { emitLog } from "../utils/logger.js";

const router = express.Router();

/**
 * Export Intelligence Report (TXT)
 */
router.post("/export", authMiddleware, async (req, res) => {
  try {
    const { summary } = req.body;

    if (!summary) {
      return res.status(400).json({ error: "Summary missing" });
    }

    const content = `
INTELLIGENCE REPORT

====================
EXECUTIVE SUMMARY
====================
${summary.executiveSummary}

====================
KEY FINDINGS
====================
- ${summary.keyFindings.join("\n- ")}

====================
ENTITY INSIGHTS
====================
People: ${summary.entityInsights?.persons?.join(", ") || "N/A"}
Places: ${summary.entityInsights?.places?.join(", ") || "N/A"}
Organizations: ${summary.entityInsights?.organizations?.join(", ") || "N/A"}

====================
ANALYST TAKEAWAYS
====================
- ${summary.analystTakeaways.join("\n- ")}

Generated by KHOJ AI
`;

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=intelligence-report.txt"
    );
    res.setHeader("Content-Type", "text/plain");

    res.send(content);

    await emitLog("log", {
      level: "INFO",
      message: `Intelligence report exported by ${req.user.username}`,
      user: req.user.username,
      agency: req.user.agency,
    });

  } catch (err) {
    console.error("Report export error:", err);
    res.status(500).json({ error: "Report export failed" });
  }
});

export default router;
