import Document from "../models/Document.js";

export const getOperationalReport = async (req, res) => {
  try {
    await emitLog("log", {
        level: "INFO",
        message: `Operational report requested by ${req.user.username}`,
        user: req.user.username,
        agency: req.user.agency,
    });
    const { from, to } = req.body;

    const start = new Date(from);
    const end = new Date(to);

    /* ===========================
       1. SUMMARY AGGREGATION
    ============================ */

    const summaryPipeline = [
      {
        $match: {
          createdAt: { $gte: start, $lte: end }
        }
      },
      {
        $group: {
          _id: null,
          totalUploaded: { $sum: 1 },
          totalIngested: {
            $sum: {
              $cond: [{ $eq: ["$ingested", true] }, 1, 0]
            }
          },
          pdfCount: {
            $sum: {
              $cond: [{ $eq: ["$fileType", "pdf"] }, 1, 0]
            }
          },
          imageCount: {
            $sum: {
              $cond: [{ $eq: ["$fileType", "image"] }, 1, 0]
            }
          }
        }
      }
    ];

    const [summary] = await Document.aggregate(summaryPipeline);

    /* ===========================
       2. TIMELINE AGGREGATION
    ============================ */

    const timelinePipeline = [
      {
        $match: {
          createdAt: { $gte: start, $lte: end }
        }
      },
      {
        $group: {
          _id: {
            year: { $year: "$createdAt" },
            month: { $month: "$createdAt" },
            day: { $dayOfMonth: "$createdAt" }
          },
          count: { $sum: 1 }
        }
      },
      {
        $sort: {
          "_id.year": 1,
          "_id.month": 1,
          "_id.day": 1
        }
      },
      {
        $project: {
          _id: 0,
          label: {
            $concat: [
              { $toString: "$_id.day" },
              "/",
              { $toString: "$_id.month" }
            ]
          },
          count: 1
        }
      }
    ];

    const timeline = await Document.aggregate(timelinePipeline);

    /* ===========================
       RESPONSE
    ============================ */

    await emitLog("log", {
      level: "SUCCESS",
      message: `Operational report generated by ${req.user.username}`,
        user: req.user.username,
        agency: req.user.agency,
        period: { from, to },
    });

    res.json({
      range: { from, to },
      summary: summary || {
        totalUploaded: 0,
        totalIngested: 0,
        pdfCount: 0,
        imageCount: 0
      },
      timeline
    });

  } catch (err) {
    console.error("Operational Report Error:", err);
    res.status(500).json({ error: "Failed to generate report" });
  }
};

import PDFDocument from "pdfkit";
import { emitLog } from "../utils/logger.js";

/**
 * Export Operational Intelligence Report (PDF)
 */
export const exportOperationalPDF = async (req, res) => {
  try {
    const { report, from, to } = req.body;
    await emitLog("log", {
        level: "INFO",
        message: `Operational report PDF export requested by ${req.user.username}`,
        user: req.user.username,
        agency: req.user.agency,
    });

    if (!report) {
      return res.status(400).json({ error: "Report data missing" });
    }

    const doc = new PDFDocument({ margin: 50 });
    const filename = `khoj-operational-report-${Date.now()}.pdf`;

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${filename}`
    );
    res.setHeader("Content-Type", "application/pdf");

    doc.pipe(res);

    /* ===============================
       HEADER
    ================================ */

    doc
      .fontSize(20)
      .text("KHOJ AI", { align: "center" })
      .moveDown(0.5);

    doc
      .fontSize(14)
      .text("Operational Intelligence Report", { align: "center" })
      .moveDown();

    doc
      .fontSize(10)
      .text(`Agency: ${req.user.agency.toUpperCase()}`)
      .text(`Generated By: ${req.user.username}`)
      .text(
        `Period: ${new Date(from).toLocaleString()} → ${new Date(
          to
        ).toLocaleString()}`
      )
      .moveDown();

    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    /* ===============================
       EXECUTIVE SUMMARY (AI READY)
    ================================ */

    doc.fontSize(14).text("Executive Summary").moveDown(0.5);

    const autoSummary = `
During the selected period, the system processed ${
      report.summary.totalUploaded
    } documents, of which ${
      report.summary.totalIngested
    } were successfully ingested. 
The majority of uploads consisted of PDF documents (${
      report.summary.pdfCount
    }), followed by image-based OCR inputs (${
      report.summary.imageCount
    }). 
Upload activity shows ${report.timeline.length} distinct activity points across the selected range.
`;

    doc.fontSize(11).text(autoSummary).moveDown();

    /* ===============================
       KEY METRICS
    ================================ */

    doc.fontSize(14).text("Key Metrics").moveDown(0.5);

    const metrics = [
      ["Total Uploaded", report.summary.totalUploaded],
      ["Successfully Ingested", report.summary.totalIngested],
      ["PDF Documents", report.summary.pdfCount],
      ["Image / OCR Documents", report.summary.imageCount],
    ];

    metrics.forEach(([label, value]) => {
      doc.fontSize(11).text(`• ${label}: ${value}`);
    });

    doc.moveDown();

    /* ===============================
       UPLOAD TIMELINE
    ================================ */

    doc.fontSize(14).text("Upload Activity Timeline").moveDown(0.5);

    report.timeline.forEach((t) => {
      doc.fontSize(11).text(`• ${t.label}: ${t.count} uploads`);
    });

    doc.moveDown();

    /* ===============================
       FOOTER
    ================================ */

    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        "This report was automatically generated by KHOJ AI. All data reflects ingestion state at the time of generation.",
        { align: "center" }
      );

    doc.end();

    /* ===============================
       AUDIT LOG
    ================================ */

    await emitLog("log", {
      level: "SUCCESS",
      message: "Operational report PDF exported",
      user: req.user.username,
      agency: req.user.agency,
      period: { from, to },
    });

  } catch (err) {
    console.error("PDF Export Error:", err);
    res.status(500).json({ error: "PDF export failed" });
  }
};
